Use device monitor to discover media sources
Igalia/openwebrtc pull request #1
Opened 2016-12-07 16:13 UTC by spira-inhabitant

Use device monitor to list sources audio and video.
Use gst_device_create_element() to create elements.

2016-12-07 16:19 UTC, philn commented on local/owr_local_media_source.h
> +    GstDevice *device;
This should be stored in the priv structure

2016-12-08 08:57 UTC, philn requested changes

2016-12-08 08:57 UTC, philn commented on local/owr_audio_renderer.c
> +    if (g_strcmp0(GST_OBJECT_NAME(gst_element_get_factory(src)), "pulsesink") != 0)
There is no such src variable in this context.

2016-12-08 08:57 UTC, philn commented on local/owr_device_list.c
> +        g_assert_not_reached();
Please initialize caps and monitor after this.

2016-12-08 08:57 UTC, philn commented on local/owr_device_list.c
> +    _owr_utils_call_closure_with_list(callback, sources);
No need to reverse the sources list before calling this?

2016-12-08 08:57 UTC, philn commented on local/owr_local_media_source.c
> -#if !defined(__ANDROID__)
Can these changes be avoided?

2016-12-08 08:57 UTC, philn commented on local/owr_local_media_source.c
> +                    if (priv->device_index > -1) {
Why isn't this done for the device case too?

2016-12-08 08:57 UTC, philn commented on local/owr_local_media_source.h
> +#include <gst/gst.h>
Nit: GstDevice could be forward-declared instead.

2016-12-08 16:46 UTC, spira-inhabitant commented on local/owr_local_media_source.h
> +    GstDevice *device;
Ok. Will be updated in next pull request.

2016-12-08 16:47 UTC, spira-inhabitant commented on local/owr_local_media_source.h
> +#include <gst/gst.h>
N/A with device declared in priv structure.

2016-12-08 16:48 UTC, spira-inhabitant commented on local/owr_local_media_source.c
> +                    if (priv->device_index > -1) {
You're right. Will be updated in next pull request.

2016-12-08 16:48 UTC, spira-inhabitant commented on local/owr_local_media_source.c
> -#if !defined(__ANDROID__)
Will be simplified in next pull request.

2016-12-08 16:51 UTC, spira-inhabitant commented on local/owr_device_list.c
> +    _owr_utils_call_closure_with_list(callback, sources);
I think not. The list from device monitor is not supposed to be sorted.

2016-12-08 16:51 UTC, spira-inhabitant commented on local/owr_device_list.c
> +        g_assert_not_reached();
Ok. Will be updated in next pull request.

2016-12-08 16:51 UTC, spira-inhabitant commented on local/owr_audio_renderer.c
> +    if (g_strcmp0(GST_OBJECT_NAME(gst_element_get_factory(src)), "pulsesink") != 0)
Ok. Will be updated in next pull request.

2016-12-08 18:13 UTC, spira-inhabitant commented
Pull request updated.

2016-12-15 12:54 UTC, philn approved these changes

2016-12-15 12:54 UTC, merged